# Applications of Principal Component Analysis



# Exercise 1: Statistical Computations on Vectors

**1.5 Exercise 1** \\
Let

$$
\textbf{x} = \begin{bmatrix}
4 \\
-2 \\
7
\end{bmatrix},
\:\:\:\:\:
\textbf{y} = \begin{bmatrix}
3 \\
4 \\
5
\end{bmatrix}.
$$

Compute the following quantities: \\
(a) The means $\bar{x}$ and $\bar{y}$. \\
(b) The variances $s_\textbf{x}^2$ and  $s_\textbf{y}^2$. \\
(c) The covariance $\text{cov}(\textbf{x},\textbf{y})$. \\
(d) The correlation between $\textbf{x}$ and $\textbf{y}$.

**Task 1(a): Compute the means $\bar{x}$ and $\bar{y}$** \\
To do: replace `...` below to input the vectors $\textbf{x}$ and $\textbf{y}$ and then compute the means $\bar{x}$ and $\bar{y}$ \\
(Hint: the command `np.mean(a)` returns the arithmetic mean of array `a`)

In [ ]:
import numpy as np

# Define the input vectors x and y
x = ...
y = ...

# (a) Compute sample means
mean_x = ... # Mean of vector x
mean_y = ... # Mean of vector y

# Output the results
print("(a) Sample Means:")
print("Mean of x:", mean_x)
print("Mean of y:", mean_y)

**Task 1(b): Compute the variances $s_\textbf{x}^2$ and  $s_\textbf{y}^2$** \\
To do: replace `...` below to compute the sample variances $s_\textbf{x}^2$ and  $s_\textbf{y}^2$ \\
(Hint: the command `np.var(a, ddof=1)` returns the sample variance of array `a`)

In [ ]:
# (b) Compute sample variances (using ddof=1 for sample variance)
var_x = ...  # Sample variance of x
var_y = ...  # Sample variance of y

print("(b) Sample Variances:")
print("Variance of x:", var_x)
print("Variance of y:", var_y)

**Task 1(c): Compute the covariance $\text{cov}(\textbf{x},\textbf{y})$** \\
To do: replace `...` below to compute the sample covariance $\text{cov}(\textbf{x},\textbf{y})$ \\
(Hint: the command `np.cov(a, b)` returns the covariance matrix of arrays `a` and `b`, in which the (0, 1)-entry is the covariance of arrays `a` and `b`)

In [ ]:
# (c) Compute sample covariance
# np.cov returns a covariance matrix; we extract the covariance, which is the [0, 1] element
cov_matrix = ...
cov_xy = ...

print("(c) Sample Covariance:")
print("Covariance between x and y:", cov_xy)

**Task 1(d): Compute the correlation between $\textbf{x}$ and $\textbf{y}$** \\
To do: replace `...` below to compute the sample correlation between $\textbf{x}$ and $\textbf{y}$ \\
(Hint: the command `np.corrcoef(a, b)` returns the Pearson product-moment correlation coefficients matrix of arrays `a` and `b`, in which the (0, 1)-entry is the sample correlation of arrays `a` and `b`)

In [ ]:
# (d) Compute sample correlation
cor_xy = ...  # Pearson correlation coefficient

print("(d) Sample Correlation:")
print("Correlation between x and y:", cor_xy)

# Exercise 2: Performance of Honors Calculus class students

**1.7 Exercise 2** \\
The set of data in the table below was collected by one of the authors from an Honors Calculus class of 14 students. The four variables are:
* ${MT}$: a score from a national test (range 1 to 36)
* ${FE}$: final exam score (range 0 to 200)
* ${Qav}$: mean of eight quiz scores (range 0 to 100)
* ${Tav}$: mean of three test scores (range 0 to 100)

**1.7.1 Original Data** \\

$$
\begin{array}{cccccccc}
\hline
Student & MT & FE & Qav & Tav \\
\hline
1 & 33 & 181 & 95 & 89 \\
2 & 31 & 169 & 81 & 89 \\
3 & 21 & 176 & 65 & 68 \\
4 & 25 & 181 & 66 & 90 \\
5 & 29 & 169 & 89 & 81 \\
6 & 24 & 103 & 61 & 57 \\
7 & 24 & 150 & 81 & 76 \\
8 & 29 & 147 & 86 & 76 \\
9 & 36 & 181 & 98 & 102 \\
10 & 26 & 163 & 72 & 70 \\
11 & 31 & 163 & 95 & 81 \\
12 & 29 & 147 & 65 & 67 \\
13 & 23 & 160 & 62 & 68 \\
14 & 26 & 100 & 63 & 56 \\ \hline
\end{array}
$$


Perferm the following tasks: \\
1. * **Original Data**: The data is stored in a NumPy array.
   * **Compute Column Means**: Calculate the mean for each column using `np.mean`.
   *  **Compute Column Standard Deviations**: Calculate the standard deviation for each column using `np.std` with `ddof=1` for sample standard deviation.
2. * **Standardize the Data**: Use the formula
$$
\textbf{z} = \frac{\textbf{x}-\bar{\textbf{x}}}{s_\textbf{x}}
$$
to standardize the data. (obtaining a scaled variable with mean 0 and standard devation 1)
   * **Round the $Z$ Matrix**: Round the standardized values to four decimal places using `np.round`.
3. * **Compute the Correlation Matrix**: Calculate the correlation matrix of the standardized data using `np.corrcoef`.
   * **Round the $C_0$ Matrix**: Round the values to four decimal places using `np.round`.
4. **Perform PCA**: Use PCA from `sklearn.decomposition` to perform principal component analysis.
5. * **Extract the Loadings**: Get the eigenvectors (loadings) from the PCA result using `pca.components_`.
   * **Extract the Eigenvalues**: Get the eigenvalues from the PCA result using `pca.explained_variance_`.
6. * **Compute Specified Sums `y1` and `y2`**: Calculate the specified sums using the loadings and standardized data.
  * **Compute Column Means of `y1` and `y2`**: Calculate the mean of the computed sums `y1` and `y2`.
  * **Compute Column Standard Deviations of `y1` and `y2`**: Calculate the standard deviation of `y1` and `y2`.
  * **Normalize `y1` and `y2`**: Normalize `y1` and `y2` using their respective means and standard deviations.
  * **Add `y1_normalized` and `y2_normalized` to Z**: Add the normalized `y1` and `y2` as new columns to the standardized data matrix.
  * **Compute Correlation Matrix with `y1_normalized` and `y2_normalized`**: Calculate the correlation matrix including the normalized `y1` and `y2`.
  * **Remove Row and Column Labels from `newC0`**: Remove the row and column labels from the new correlation matrix.
7. **Compute the Proportion of Variance Explained**: Calculate the proportion of variance explained by each principal component.
8. **Compute the Principal Components**: Get the principal components from the PCA result using `pca.transform`.
9. * **Print the Results**: Display the correlation matrix, loadings, eigenvalues, proportion of variance explained, and principal components.
   * **Plot Principal Axes**: Plot the principal axes (PC1 and PC2) in a scatter plot with different colors.


**Task 2.1: Compute the means and standard deviations of the variables** \\
To do: replace `...` below to compute the means and standard deviations of the variables $MT, FE, Qav, Tav$ \\
(Hint: the command `np.mean(a, axis=0)` returns the arithmetic mean of array `a` along the columns and \\
the command `np.std(a, axis=0, ddof=1)` returns the sample standard deviation of array `a` along the columns)

In [14]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import pandas as pd

# Step 1,1: Original data
values = np.array([[33,31,21,25,29,24,24,29,36,26,31,29,23,26],
          [181,169,176,181,169,103,150,147,181,163,163,147,160,100],
          [95,81,65,66,89,61,81,86,98,72,95,65,62,63],
          [89,89,68,90,81,57,76,76,102,70,81,67,68,56]])
# Step 1.2: Compute column means
values =values.transpose()
mean_values = np.mean(values,axis=0)
print("Column Means:", mean_values)

# Step 1.3: Compute column standard deviations
std_dev_values = np.std(values,axis=0,ddof=0)
print("Column Standard Deviations:", std_dev_values)

Column Means: [ 27.64285714 156.42857143  77.07142857  76.42857143]
Column Standard Deviations: [ 4.06390282 25.16719601 13.24744873 12.71508826]


**Task 2.2: Find the standardized matrix $Z$ of the data** \\
To do: replace `...` below to compute the the standardized matrix $Z$ with scaled variables (standard score)

In [17]:
# Step 2.1: Standardize the data
Z = [(values - mean_values) / std_dev_values]
#print(Z)
# Step 2.2: Round the Z matrix to four decimal places
Z = np.round(Z,4)
print("Standardized Data (Z):\n", Z)

Standardized Data (Z):
 [[[ 1.3182  0.9763  1.3534  0.9887]
  [ 0.8261  0.4995  0.2966  0.9887]
  [-1.6346  0.7777 -0.9112 -0.6629]
  [-0.6503  0.9763 -0.8357  1.0673]
  [ 0.334   0.4995  0.9004  0.3595]
  [-0.8964 -2.1229 -1.2132 -1.528 ]
  [-0.8964 -0.2554  0.2966 -0.0337]
  [ 0.334  -0.3746  0.674  -0.0337]
  [ 2.0564  0.9763  1.5798  2.0111]
  [-0.4043  0.2611 -0.3828 -0.5056]
  [ 0.8261  0.2611  1.3534  0.3595]
  [ 0.334  -0.3746 -0.9112 -0.7415]
  [-1.1425  0.1419 -1.1377 -0.6629]
  [-0.4043 -2.2421 -1.0622 -1.6066]]]


**Task 2.3: Find the correlation matrix $C_0$ of the variables** \\
To do: replace `...` below to compute the correlation matrix $C_0$ of the variables \\
(Hint: the command `np.corrcoef(a, rowvar=False)` returns the Pearson product-moment correlation coefficients matrix of `a`, where each column of `a` represents a variable)

In [19]:
# Step 3: Compute the correlation matrix
C0 = np.corrcoef(Z,rowvar=0)
C0 = C0[0,1]
print("Correlation Matrix (C0):\n", C0)

ValueError: m has more than 2 dimensions

**Task 2.4: Perform PCA** \\
To do: replace `...` below to perform PCA on $Z$ \\
(Hint: the command `PCA()` initialize a PCA object and  \\
the command `pca.fit(X)` compute the principal components based on the dataset `X`)

In [ ]:
# Step 4: Perform PCA
pca = ...
...

**Task 2.5: Extract the loadings (eigenvectors) and eigenvalues** \\
To do: replace `...` below to find the loadings (eigenvectors) and eigenvalues from PCA result (SVD of $C_0$) \\
(Hint: the command `pca.components_.T` extracts the loadings (eigenvectors) and \\
the command  `pca.explained_variance_` extracts the eigenvalues from the PCA result)


In [ ]:
# Step 5.1: Extract the loadings (eigenvectors)
loadings = ...
loadings = ...
print("Loadings (Eigenvectors):\n", loadings)

# Step 5.2: Extract the eigenvalues
eigenvalues = ...
eigenvalues = ...
print("\nEigenvalues:\n", eigenvalues)

**Task 2.6: Compute specified sums $\mathbf{y}_1$ and $\mathbf{y}_2$** \\
To do: replace `...` below to calculate information about $\mathbf{y}_1$ and $\mathbf{y}_2$

In [ ]:
# Step 6.1: Compute the specified sums
y1 = ...
y2 = ...


# Step 6.2: Compute column means of y1 and y2
mean_y1 = ...
mean_y2 = ...
print("mean of y1 = ")
print(mean_y1)
print("\nmean of y2 = ")
print(mean_y2)

# Step 6.3: Compute column standard deviations of y1 and y2
std_dev_y1 = ...
std_dev_y2 = ...
print("\nstandard deviation of y1 = ")
print(std_dev_y1)
print("\nstandard deviation of y2 = ")
print(std_dev_y2)

# Step 6.4: Normalize y1 and y2
y1_normalized = ...
y2_normalized = ...

print("\nnormalized y1 : ")
print(y1_normalized)
print("normalized y2 : ")
print(y2_normalized)

# Step 6.5: Add y1_normalized and y2_normalized to Z as fifth and sixth columns
newZ = ...
print("\nnew Z: ")
print(newZ)

# Step 6.6: Compute the correlation matrix with y1_normalized and y2_normalized
newC0 = ...
newC0 = np.round(newC0, 4)
print("\nnew C_0: ")
print(newC0)

# Step 6.7: Add row and column labels from newC0
newC0_df = pd.DataFrame(newC0)
newC0_df.index = ["MT*", "FE*", "Qav*", "Tav*", "y1", "y2"]
newC0_df.columns = ["MT*", "FE*", "Qav*", "Tav*", "y1", "y2"]
print("\nnew C_0 with labels: ")
print(newC0_df)

**Task 2.7: Compute the Proportion of Variance Explained** \\
To do: replace `...` below to calculate the proportion of variance explained (eigenvalues) by each principal component

In [ ]:
# Step 6: Compute the proportion of variance explained
proportion_variance = ...
proportion_variance = ...
print("Proportion of Variance Explained:\n", proportion_variance)

**Task 2.8: Find the principal components** \\
To do: replace `...` below to find the principal components from the PCA result \\
(Hint: the command `pca.transform(X)` returns the principal components from the PCA result)

In [ ]:
# Step 11: Compute the principal components
principal_components = ...
principal_components = ...
print("Principal Components:\n", principal_components)

**Task 2.9: Print the results**

In [ ]:
# Step 8: Print the results
print("Correlation Matrix (C0):")
print(C0)
print("\nLoadings (Eigenvectors)")
print(loadings)
print("\nEigenvalues:")
print(eigenvalues)
print("\nProportion of Variance Explained:")
print(proportion_variance)
print("\nPrincipal Components:")
print(principal_components)

In [ ]:
# Plotting the principal axes
plt.scatter(principal_components[:, 0], principal_components[:, 1], color='blue')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.title('Scatter Plot with Principal Axes')
plt.axhline(0, color='gray')
plt.axvline(0, color='gray')
plt.arrow(0, 0, loadings[0, 0], loadings[1, 0], color='red', linewidth=2, label='PC1')
plt.arrow(0, 0, loadings[0, 1], loadings[1, 1], color='green', linewidth=2, label='PC2')
plt.legend(loc='upper right')
plt.show()

# Exercise 3: Tests scores in Algebra, Trigonometry, English Literature and Chinese Literature

**1.8 Exercise 3** \\
Principal Component Analysis: Test Scores in Mathematics, English Literature , and Chinese Literature

A group of ten students took four tests: two in mathematics (Algebra (abbreviated as $Alg$) and Trigonometry (abbreviated as $Trig$)), one in English Literature (abbreviated as $Englit$), and one in Chinese Literature (abbreviated as $Chilit$). The following table presents both the original and the scaled scores.

**1.8.1 Original and Scaled Test Scores** \\

$$
\begin{array}{cccccccc}
\hline
Student & Alg & Trig & Englit & Chilit \\
\hline
1  & 95 & 88 & 65 & 68 \\
2  & 87 & 92 & 70 & 74 \\
3  & 75 & 78 & 75 & 72 \\
4  & 74 & 70 & 85 & 81 \\
5  & 46 & 51 & 92 & 95 \\
6  & 62 & 55 & 88 & 90 \\
7  & 82 & 91 & 85 & 90 \\
8  & 68 & 52 & 55 & 60 \\
9  & 82 & 78 & 80 & 75 \\
10 & 65 & 70 & 72 & 70 \\
\hline
\end{array}
$$

Perferm the following tasks: (refer to exercise 2) \\
1. * **Original Data**: The data is stored in a NumPy array.
   * **Compute Column Means**: Calculate the mean for each column using `np.mean`.
   *  **Compute Column Standard Deviations**: Calculate the standard deviation for each column using `np.std` with `ddof=1` for sample standard deviation.
2. * **Standardize the Data**: Use the formula
$$
\textbf{z} = \frac{\textbf{x}-\bar{\textbf{x}}}{s_\textbf{x}}
$$
to standardize the data. (obtaining a scaled variable with mean 0 and standard devation 1)
   * **Round the $Z$ Matrix**: Round the standardized values to four decimal places using `np.round`.
3. * **Compute the Correlation Matrix**: Calculate the correlation matrix of the standardized data using `np.corrcoef`.
   * **Round the $C_0$ Matrix**: Round the values to four decimal places using `np.round`.
4. **Perform PCA**: Use PCA from `sklearn.decomposition` to perform principal component analysis.
5. * **Extract the Loadings**: Get the eigenvectors (loadings) from the PCA result using `pca.components_`.
   * **Extract the Eigenvalues**: Get the eigenvalues from the PCA result using `pca.explained_variance_`.
6. * **Compute Specified Sums `y1` and `y2`**: Calculate the specified sums using the loadings and standardized data.
  * **Compute Column Means of `y1` and `y2`**: Calculate the mean of the computed sums `y1` and `y2`.
  * **Compute Column Standard Deviations of `y1` and `y2`**: Calculate the standard deviation of `y1` and `y2`.
  * **Normalize `y1` and `y2`**: Normalize `y1` and `y2` using their respective means and standard deviations.
  * **Add `y1_normalized` and `y2_normalized` to Z**: Add the normalized `y1` and `y2` as new columns to the standardized data matrix.
  * **Compute Correlation Matrix with `y1_normalized` and `y2_normalized`**: Calculate the correlation matrix including the normalized `y1` and `y2`.
  * **Remove Row and Column Labels from `newC0`**: Remove the row and column labels from the new correlation matrix.
7. **Compute the Proportion of Variance Explained**: Calculate the proportion of variance explained by each principal component.
8. **Compute the Principal Components**: Get the principal components from the PCA result using `pca.transform`.
9. * **Print the Results**: Display the correlation matrix, loadings, eigenvalues, proportion of variance explained, and principal components.
   * **Plot Principal Axes**: Plot the principal axes (PC1 and PC2) in a scatter plot with different colors.


In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

# Step 1,1: Original data
data = ...

# Step 1.2: Compute column means
mean_values = ...
print("Column Means:", mean_values)

# Step 1.3: Compute column standard deviations
std_dev_values = ...
print("Column Standard Deviations:", std_dev_values)

In [ ]:
# Step 2.1: Standardize the data
Z = ...

# Step 2.2: Round the Z matrix to four decimal places
Z = ...
print("Standardized Data (Z):\n", Z)

In [ ]:
# Step 3: Compute the correlation matrix
C0 = ...
C0 = ...
print("Correlation Matrix (C0):\n", C0)

In [ ]:
# Step 4: Perform PCA
pca = ...
...

In [ ]:
# Step 5.1: Extract the loadings (eigenvectors)
loadings = ...
loadings = ...
print("Loadings (Eigenvectors):\n", loadings)

# Step 5.2: Extract the eigenvalues
eigenvalues = ...
eigenvalues = ...
print("\nEigenvalues:\n", eigenvalues)

In [ ]:
# Step 6: Compute the proportion of variance explained
proportion_variance = ...
proportion_variance = ...
print("Proportion of Variance Explained:\n", proportion_variance)

In [ ]:
# Step 11: Compute the principal components
principal_components = ...
principal_components = ...
print("Principal Components:\n", principal_components)

In [ ]:
# Step 8: Print the results
print("Correlation Matrix (C0):")
print(C0)
print("\nLoadings (Eigenvectors)")
print(loadings)
print("\nEigenvalues:")
print(eigenvalues)
print("\nProportion of Variance Explained:")
print(proportion_variance)
print("\nPrincipal Components:")
print(principal_components)